add_newline = false
command_timeout = 1000

[character]
success_symbol = "❯"
error_symbol = "❯"
vimcmd_symbol = "❮"

[line_break]
disabled = true

[directory]
truncation_length = 3
truncate_to_repo = false

[git_branch]
format = " [$symbol$branch]($style)"

[git_status]
format = "[$all_status$ahead_behind]($style)"

[nodejs]
format = " [$symbol($version )]($style)"

[python]
format = " [$symbol($version )]($style)"

[rust]
format = " [$symbol($version )]($style)"

